/*
 *  Auth
 */
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';

/*
 *  Base
 */
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';


/*
 *  Graficos
 */
export const GET_DATA = 'GET_DATA';
export const GET_ALL_DATA = 'GET_ALL_DATA';
export const GET_SALES_X_HOUR = 'GET_SALES_X_HOUR';
export const GET_PAYMENTS_METHODS_OF_DAY = 'GET_PAYMENTS_METHODS_OF_DAY';
export const GET_WEEKLY_TRENDS = 'GET_WEEKLY_TRENDS';
export const GET_MOST_SOLD_CATEGORIES = 'GET_MOST_SOLD_CATEGORIES';
export const GET_MOST_SELLED_PRODUCTS = 'GET_MOST_SELLED_PRODUCTS';
export const GET_AVERAGE_ATENTION = 'GET_AVERAGE_ATENTION';
export const GET_DISHES_X_DAY = 'GET_DISHES_X_DAY';
export const GET_LAST_SEVEN_DAYS = 'GET_LAST_SEVEN_DAYS';
export const GET_DELIVERIES = 'GET_DELIVERIES';
export const GET_WAREHOUSE = 'GET_WAREHOUSE';
export const GET_WAREHOUSES = 'GET_WAREHOUSES';
export const GET_INFO_WAREHOUSE = 'GET_INFO_WAREHOUSE';
export const GET_SALES_HISTORY = 'GET_SALES_HISTORY';
